version: '3.5'

services:
    db:
      image: postgres
      restart: unless-stopped
      environment:
        - POSTGRES_USER=example-backend
        - POSTGRES_PASSWORD=secret
      volumes:
        - ./database:/var/lib/postgresql/data
    redis:
      image: redis
    backend:
      build: ../../Part1/1.11
      ports:
        - 8000:8000
      environment:
        - DB_USERNAME=example-backend
        - DB_PASSWORD=secret
        - DB_HOST=db
        - REDIS=redis
    frontend:
      build: ../../Part1/1.10
      ports:
        - 5000:5000
    nginx:
      image: nginx
      ports:
        - 80:80
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
