version: '3.5'

services:
    redis:
      image: redis
    backend:
      build: ../../Part1/1.11
      ports:
        - 8000:8000
      environment:
        - FRONT_URL=http://localhost:5000
        - REDIS=redis
    frontend:
      build: ../../Part1/1.10
      ports:
        - 5000:5000
      environment:
        - API_URL=http://localhost:8000