version: '3.5'

services:
  backend:
    build: ../../Part1/1.11
    ports:
      - 8000:8000
  frontend:
    build: ../../Part1/1.10
    ports:
      - 5000:5000
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
